name: n_notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  launcher_name: ^1.0.2 
  
launcher_name:
  default: "N Notes"

flutter:
  uses-material-design: true
  fonts:
    - family: Nothing
      fonts:
        - asset: assets/fonts/nothing-font-5x7.ttf
