name: n_notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  sizer: ^2.0.15

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.6
  launcher_name: ^1.0.2

launcher_name:
  default: "N Notes"
icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true

flutter:
  uses-material-design: true
  fonts:
    - family: Nothing
      fonts:
        - asset: assets/fonts/nothing-font-5x7.ttf
